### ISSUE TITLE
what is the difference of `bucket` and `color` in initialization progress.

### ISSUE THREAD

**Issue by sadscv** [CarolinaBianchi/ETPsolver#2]
hi Carolina. I'm a programmer from China. 
I'm trying to rewrite your ETPsolver into Python and got stuck when I'm trying to understand the meaning of `bucket` in BucketInitializer.java. I found that in `readme.md`  you mentioned `Moreover, we group colors in buckets (subsets of colors with a fixed size).` but that was still confusing me when I'm reading the code.  could you please explain the difference between `bucket` and `color` in initializing progress more detailed? 
thank you very much!

**Comment by CarolinaBianchi** [comment]
Hi, 
sorry for the late answer. It has been a long time since I last mantained this code, but for what I remember:
- Colors correspond to timeslots
- Buckets are subset of colors, i.e. of timeslots
In order to construct the buckets the current implementation fixes the size of the buckets to 6 (debatable), and picks timeslots which are equally spaced by 6 units.
Right now I would do it differently, adding some random component.
I suggest you to give a look at the pptx that we have prepared (with the animation), as it gives an intuitive view of how the algorithm works (https://github.com/CarolinaBianchi/ETPsolver/blob/master/Optimization/doc/ETPslides_OMAAL_group11.pptx).
I hope this is useful

**Comment by sadscv** [comment]
lol, so good to see your reply.
your explanation is very clear, and the PPT you provided is quite intuitive. that solved my questions very well. thank you so much for your reply.
